In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column

In [3]:
# show dataframe
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

# query()

In [ ]:
# select players older than 34
df.query("age>34")

# exercise: write the equivalent boolean slicing
#df[df['age']>34]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
Z. Ibrahimović,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy,85,...,53+4,57+4,57+4,57+4,53+4,50+4,52+4,52+4,52+4,50+4
Pepe,120533,https://sofifa.com/player/120533/kepler-lavera...,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto,84,...,73+3,76+3,76+3,76+3,73+3,75+3,82+3,82+3,82+3,75+3
G. Buffon,1179,https://sofifa.com/player/1179/gianluigi-buffo...,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Casillas,5479,https://sofifa.com/player/5479/iker-casillas-f...,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F. Quagliarella,159261,https://sofifa.com/player/159261/fabio-quaglia...,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria,83,...,54+2,54+2,54+2,54+2,54+2,50+2,45+2,45+2,45+2,50+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N. Hunt,138083,https://sofifa.com/player/138083/nicky-hunt/20...,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra,55,...,54+2,55+2,55+2,55+2,54+2,53+2,58+2,58+2,58+2,53+2
K. Ogi,232539,https://sofifa.com/player/232539/kota-ogi/20/1...,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J. McCombe,11430,https://sofifa.com/player/11430/jamie-mccombe/...,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City,52,...,38+2,44+2,44+2,44+2,38+2,41+2,50+2,50+2,50+2,41+2
G. Maley,245558,https://sofifa.com/player/245558/gary-maley/20...,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zhou Ting,182461,https://sofifa.com/player/182461/ting-zhou/20/...,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC,49,...,48+2,50+2,50+2,50+2,48+2,48+2,51+2,51+2,51+2,48+2

In [5]:
# select players older than 34 from Italy
df.query("age>34 and nationality=='Italy'")

# exercise: write the equivalent boolean slicing
# df[(df['age']>34) & (df['nationality']=='Italy')]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
G. Buffon,1179,https://sofifa.com/player/1179/gianluigi-buffo...,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F. Quagliarella,159261,https://sofifa.com/player/159261/fabio-quaglia...,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria,83,...,54+2,54+2,54+2,54+2,54+2,50+2,45+2,45+2,45+2,50+2
D. De Rossi,53302,https://sofifa.com/player/53302/daniele-de-ros...,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors,82,...,75+3,81+3,81+3,81+3,75+3,76+3,82+3,82+3,82+3,76+3
A. Mirante,140293,https://sofifa.com/player/140293/antonio-miran...,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma,79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A. Diamanti,163925,https://sofifa.com/player/163925/alessandro-di...,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC,76,...,56+2,55+2,55+2,55+2,56+2,51+2,45+2,45+2,45+2,51+2
C. Maggio,149184,https://sofifa.com/player/149184/christian-mag...,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento,74,...,73+2,72+2,72+2,72+2,73+2,73+2,73+2,73+2,73+2,73+2
D. Dainelli,7647,https://sofifa.com/player/7647/dario-dainelli/...,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno,73,...,56+2,64+2,64+2,64+2,56+2,59+2,72+2,72+2,72+2,59+2
F. Marchetti,139668,https://sofifa.com/player/139668/federico-marc...,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F. Peluso,178418,https://sofifa.com/player/178418/federico-pelu...,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo,73,...,66+2,67+2,67+2,67+2,66+2,68+2,72+2,72+2,72+2,68+2
C. Terzi,102064,https://sofifa.com/player/102064/claudio-terzi...,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia,72,...,62+2,64+2,64+2,64+2,62+2,64+2,70+2,70+2,70+2,64+2
A. Rosina,137460,https://sofifa.com/player/137460/alessandro-ro...,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919,72,...,51+2,49+2,49+2,49+2,51+2,47+2,35+2,35+2,35+2,47+2
D. Maietta,137774,https://sofifa.com/player/137774/domenico-maie...,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli,72,...,55+2,62+2,62+2,62+2,55+2,58+2,70+2,70+2,70+2,58+2
A. Cordaz,149258,https://sofifa.com/player/149258/alex-cordaz/2...,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S. Floccari,169386,https://sofifa.com/player/169386/sergio-flocca...,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL,72,...,45+2,44+2,44+2,44+2,45+2,43+2,41+2,41+2,41+2,43+2
M. Iori,188499,https://sofifa.com/player/188499/manuel-iori/2...,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella,72,...,67+2,70+2,70+2,70+2,67+2,66+2,67+2,67+2,67+2,66+2
M. Stefani,149587,https://sofifa.com/player/149587/mirco-stefani...,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone,71,...,62+2,66+2,66+2,66+2,62+2,65+2,70+2,70+2,70+2,65+2
G. Pegolo,106795,https://sofifa.com/player/106795/gianluca-pego...,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D. Gastaldello,137410,https://sofifa.com/player/137410/daniele-gasta...,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia,70,...,55+2,63+2,63+2,63+2,55+2,57+2,68+2,68+2,68+2,57+2
D. Moscardelli,138871,https://sofifa.com/player/138871/davide-moscar...,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa,70,...,49+2,51+2,51+2,51+2,49+2,47+2,50+2,50+2,50+2,47+2
E. Calaiò,149224,https://sofifa.com/player/149224/emanuele-cala...,Emanuele Calaiò,37,1982-01-08,179,75,Italy,US Salernitana 1919,70,...,46+2,46+2,46+2,46+2,46+2,43+2,44+2,44+2,44+2,43+2
D. Croce,137406,https://sofifa.com/player/137406/daniele-croce...,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese,69,...,68+2,66+2,66+2,66+2,68+2,67+2,64+2,64+2,64+2,67+2
A. Rosati,149309,https://sofifa.com/player/149309/antonio-rosat...,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F. Mazzeo,194851,https://sofifa.com/player/194851/fabio-mazzeo/...,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno,69,...,48+2,47+2,47+2,47+2,48+2,44+2,40+2,40+2,40+2,44+2
M. De Agostini,251463,https://sofifa.com/player/251463/michele-de-ag...,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone,69,...,68+2,66+2,66+2,66+2,68+2,67+2,66+2,66+2,66+2,67+2
A. Pomini,188017,https://sofifa.com/player/188017/alberto-pomin...,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
F. Evacuo,158370,https://sofifa.com/player/158370/felice-evacuo...,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani,67,...,47+2,51+2,51+2,51+2,47+2,46+2,49+2,49+2,49+2,46+2
G. Munari,159040,https://sofifa.com/player/159040/gianni-munari...,Gianni Munari,36,1983-06-24,190,84,Italy,Parma,67,...,61+2,66+2,66+2,66+2,61+2,61+2,68+2,68+2,68+2,61+2
L. Pagliarulo,161725,https://sofifa.com/player/161725/luca-pagliaru...,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani,67,...,54+2,59+2,59+2,59+2,54+2,56+2,66+2,66+2,66+2,56+2
C. Del Grosso,173305,https://sofifa.com/player/173305/cristiano-del...,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara,66,...,65+2,63+2,63+2,63+2,65+2,65+2,64+2,64+2,64+2,65+2
R. Vitiello,138920,https://sofifa.com/player/138920/roberto-vitie...,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia,65,...,57+2,58+2,58+2,58+2,57+2,59+2,64+2,64+2,64+2,59+2
A. Bruno,203649,https://sofifa.com/player/203649/alessandro-br...,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara,65,...,60+2,65+2,65+2,65+2,60+2,59+2,62+2,62+2,62+2,59+2
T. Berni,54037,https://sofifa.com/player/54037/tommaso-berni/...,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter,64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P. Gori,120243,https://sofifa.com/player/120243/pier-graziano...,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S. Farelli,137356,https://sofifa.com/player/137356/simone-farell...,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara,58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# add a not operator to the first example
df.query("not(age>34)")

# exercise: write the equivalent boolean slicing
# df[~(df['age']>34)]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [7]:
# convert height to meters and select those with height above 1.8
df.query("height_cm/100 > 1.8")

# exercise: write the equivalent boolean slicing
# df[df['height_cm']/100>1.8]

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
K. De Bruyne,192985,https://sofifa.com/player/192985/kevin-de-bruy...,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91,...,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3
M. ter Stegen,192448,https://sofifa.com/player/192448/marc-andre-te...,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
V. van Dijk,203376,https://sofifa.com/player/203376/virgil-van-di...,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool,90,...,79+3,83+3,83+3,83+3,79+3,81+3,87+3,87+3,87+3,81+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P. Martin,251789,https://sofifa.com/player/251789/paul-martin/2...,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [9]:
# Check data types
df.dtypes

# Convert dob column to datetime
df['dob'] = pd.to_datetime(df['dob'])

# Check again
df.dtypes

# Query people born after 1990
df.query("dob.dt.year > 1990")

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
K. De Bruyne,192985,https://sofifa.com/player/192985/kevin-de-bruy...,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91,...,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3
M. ter Stegen,192448,https://sofifa.com/player/192448/marc-andre-te...,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2